In [1]:
import numpy as np
import pandas as pd
import numba

In [2]:
song = pd.read_json("res/song_meta.json")[["id", "song_name", "artist_id_basket", "artist_name_basket",\
                                            "album_id", "album_name", "song_gn_gnr_basket",\
                                            "song_gn_dtl_gnr_basket", "issue_date"]]
genre = pd.read_json("res/genre_gn_all.json", typ="series")
train = pd.read_json("res/train.json")[["id", "plylst_title", "songs", "tags", "like_cnt", "updt_date"]]
val = pd.read_json("res/val.json")[["id", "plylst_title", "songs", "tags", "like_cnt", "updt_date"]]
test = pd.read_json("res/test.json")[["id", "plylst_title", "songs", "tags", "like_cnt", "updt_date"]]
display(song, genre, train, val, test)

id                                          song_name  \
0            0                                           Feelings   
1            1  Bach : Partita No. 4 In D Major, BWV 828 - II....   
2            2                    Solsbury Hill (Remastered 2002)   
3            3  Feeling Right (Everything Is Nice) (Feat. Popc...   
4            4                                            그남자 그여자   
...        ...                                                ...   
707984  707984                           Coffin For Head Of State   
707985  707985                                    Change Of Heart   
707986  707986                                             스치듯 안녕   
707987  707987                                               숲의 빛   
707988  707988                                       Queen 명곡 멜로디   

       artist_id_basket artist_name_basket  album_id  \
0                [2727]  [Various Artists]   2255639   
1               [29966]   [Murray Perahia]    376431   
2                [3361]    [Peter Gabriel]   4698747   
3              [838543]           [Matoma]   2644882   
4              [560160]         [Jude Law]   2008470   
...                 ...                ...       ...   
707984         [166499]        [Fela Kuti]     65254   
707985          [11837]     [Cyndi Lauper]     44141   
707986            [437]              [윤종신]   2662866   
707987         [729868]     [Nature Piano]   2221722   
707988            [895]              [김경호]     34663   

                                               album_name song_gn_gnr_basket  \
0                            불후의 명곡 - 7080 추억의 얄개시대 팝송베스트           [GN0900]   
1                           Bach : Partitas Nos. 2, 3 & 4           [GN1600]   
2                                                     Hit           [GN0900]   
3       Feeling Right (Everything Is Nice) (Feat. Popc...           [GN1100]   
4                                                 그남자 그여자           [GN1800]   
...                                                   ...                ...   
707984               The Best Best Of The Black President           [GN2000]   
707985                                        True Colors           [GN0900]   
707986                  행보 2015 윤종신 / 작사가 윤종신 Live Part.1           [GN0100]   
707987                                 명상의 시간을 위한 뉴에이지 음악           [GN1800]   
707988                                           김경호 Live           [GN0600]   

       song_gn_dtl_gnr_basket  issue_date  
0                    [GN0901]    20140512  
1            [GN1601, GN1606]    20080421  
2                    [GN0901]    20180518  
3            [GN1102, GN1101]    20151016  
4            [GN1802, GN1801]    20110824  
...                       ...         ...  
707984               [GN2001]    19991219  
707985               [GN0901]    19860000  
707986       [GN0105, GN0101]    20160120  
707987       [GN1807, GN1801]    20131217  
707988       [GN0601, GN0604]    19980000  

[707989 rows x 9 columns]

GN0100       발라드
GN0101    세부장르전체
GN0102       '80
GN0103       '90
GN0104       '00
           ...  
GN2900       뮤지컬
GN2901    세부장르전체
GN2902     국내뮤지컬
GN2903     국외뮤지컬
GN3000     크리스마스
Length: 254, dtype: object

id                       plylst_title  \
0        61281                            여행같은 음악   
1        10532                            요즘 너 말야   
2        76951              편하게, 잔잔하게 들을 수 있는 곡.-   
3       147456              크리스마스 분위기에 흠뻑 취하고 싶을때   
4        27616                           추억의 노래 ㅋ   
...        ...                                ...   
115066  120325                      METAL E'SM #2   
115067  106976     빠른 리스너를 위한 따끈따끈한 최신 인기 EDM 모음!   
115068   11343              #1. 눈물이 앞을 가리는 나의_이야기   
115069  131982  퇴근 버스에서 편히 들으면서 하루를 마무리하기에 좋은 POP   
115070  100389                FAVORITE POPSONG!!!   

                                                    songs  \
0       [525514, 129701, 383374, 562083, 297861, 13954...   
1       [432406, 675945, 497066, 120377, 389529, 24427...   
2       [83116, 276692, 166267, 186301, 354465, 256598...   
3       [394031, 195524, 540149, 287984, 440773, 10033...   
4       [159327, 553610, 5130, 645103, 294435, 100657,...   
...                                                   ...   
115066  [429629, 441511, 612106, 516359, 691768, 38714...   
115067  [321330, 216057, 534472, 240306, 331098, 23288...   
115068  [50512, 249024, 250608, 371171, 229942, 694943...   
115069  [533534, 608114, 343608, 417140, 609009, 30217...   
115070  [26008, 456354, 324105, 89871, 135272, 143548,...   

                                                     tags  like_cnt  \
0                                                     [락]        71   
1                                                [추억, 회상]         1   
2                                               [까페, 잔잔한]        17   
3       [연말, 눈오는날, 캐럴, 분위기, 따듯한, 크리스마스캐럴, 겨울노래, 크리스마스,...        33   
4                                                    [댄스]         9   
...                                                   ...       ...   
115066               [록메탈, 밴드사운드, 록, 락메탈, 메탈, 락, extreme]         3   
115067                                               [일렉]        13   
115068             [담시, 가족, 눈물, 그리움, 주인공, 나의_이야기, 사랑, 친구]         4   
115069                      [잔잔한, 버스, 퇴근버스, Pop, 풍경, 퇴근길]         4   
115070                             [노래추천, 팝송추천, 팝송, 팝송모음]        17   

                      updt_date  
0       2013-12-19 18:36:19.000  
1       2014-12-02 16:19:42.000  
2       2017-08-28 07:09:34.000  
3       2019-12-05 15:15:18.000  
4       2011-10-25 13:54:56.000  
...                         ...  
115066  2020-04-17 04:31:11.000  
115067  2015-12-24 17:23:19.000  
115068  2019-08-16 20:59:22.000  
115069  2019-10-25 23:40:42.000  
115070  2020-04-18 20:35:06.000  

[115071 rows x 6 columns]

id plylst_title                                              songs  \
0      118598               [373313, 151080, 275346, 696876, 165237, 52593...   
1      131447       앨리스테이블                                                 []   
2       51464               [529437, 516103, 360067, 705713, 226062, 37089...   
3       45144               [589668, 21711, 570151, 320043, 13930, 599327,...   
4       79929               [672718, 121924, 102694, 683657, 201558, 38511...   
...       ...          ...                                                ...   
23010  101722               [75842, 26083, 244183, 684715, 500593, 508608,...   
23011  122127               [450275, 487671, 561031, 663944, 628672, 59121...   
23012   77438               [625875, 464051, 11657, 236393, 358186, 213435...   
23013   36231               [161094, 665833, 688145, 432735, 439938, 12665...   
23014   65189               [643070, 132994, 98223, 293236, 513129, 650494...   

                              tags  like_cnt                updt_date  
0                               []      1675  2019-05-27 14:14:33.000  
1                               []         1  2014-07-16 15:24:24.000  
2                               []        62  2008-06-21 23:26:22.000  
3                               []        20  2017-10-30 18:15:43.000  
4                               []        20  2017-02-07 11:40:42.000  
...                            ...       ...                      ...  
23010                        [잔잔한]        17  2015-12-17 14:06:05.000  
23011  [어머니, 힘들때, 아빠, 가족, 위로받고싶을때]        10  2020-04-16 21:35:44.000  
23012                           []         0  2019-03-27 15:27:40.000  
23013                           []        31  2015-11-18 11:49:09.000  
23014                           []        19  2017-04-23 16:50:58.000  

[23015 rows x 6 columns]

id plylst_title                                              songs  \
0       70107               [398985, 449403, 411543, 528044, 143048, 98020...   
1        7461               [196298, 269984, 267805, 175867, 529244, 63825...   
2       90348               [273433, 331003, 68432, 411659, 117793, 616860...   
3       58617               [702227, 48152, 440008, 358488, 701041, 540721...   
4      102395               [630683, 481582, 528550, 285114, 506667, 17922...   
...       ...          ...                                                ...   
10735  137930               [323755, 397594, 445908, 570242, 221853, 20018...   
10736     936               [105140, 582252, 199262, 422915, 547967, 48791...   
10737  110589               [21976, 207746, 40025, 31635, 567462, 641799, ...   
10738    2605               [234554, 265033, 507260, 83092, 366757, 497097...   
10739  126651               [685111, 20039, 634240, 519385, 321994, 525309...   

                           tags  like_cnt                updt_date  
0                            []         6  2012-09-29 01:57:26.000  
1      [나만의Best3, 인디아티스트들의추천음악]         0  2019-12-17 14:06:45.000  
2                        [드라이브]        21  2015-05-23 10:44:48.000  
3                         [분위기]         0  2019-03-14 09:47:34.000  
4                            []        38  2018-07-11 16:43:32.000  
...                         ...       ...                      ...  
10735                      [추억]        16  2016-04-18 11:02:09.000  
10736  [띵곡의, 우울, 분위기, 드라이브, 산책]         1  2020-04-08 07:15:59.000  
10737                    [기분전환]         6  2016-06-29 00:57:21.000  
10738                      [여름]         4  2015-06-06 09:52:01.000  
10739                        []        14  2015-10-26 17:43:30.000  

[10740 rows x 6 columns]

In [23]:
train_songs = [[-1 for _ in range(200)] for _ in range(115071)]
for idx in train.index:
    for i, song in enumerate(train.songs[idx]):
        train_songs[idx][i] = song
train_songs = np.array(train_songs, dtype=np.int64)
train_songs

array([[525514, 129701, 383374, ...,     -1,     -1,     -1],
       [432406, 675945, 497066, ...,     -1,     -1,     -1],
       [ 83116, 276692, 166267, ...,     -1,     -1,     -1],
       ...,
       [ 50512, 249024, 250608, ...,     -1,     -1,     -1],
       [533534, 608114, 343608, ...,     -1,     -1,     -1],
       [ 26008, 456354, 324105, ..., 640239,  13759, 154078]])

In [37]:
all_songs = np.array([list(set(songs) - set([-1])) for songs in train_songs])
all_songs.shape

(115071,)

In [6]:
a = np.array([1,3,5,7,9,4,8])
b = np.array([2,4,6,8,10])
aa = np.arange(7) + 1
bb = np.arange(7) + 1


(array([5, 6]),)

array([6, 7])

array([6, 7])